### ISSUE TITLE
Decor Lights, Crash on load.

### ISSUE THREAD

**Issue by VasVadum** [Cairath/ONI-Mods#139] opened 2022-08-17 00:24 UTC
**Describe the bug**
I subscribed to the mod, tried to enable it. Crash on load.

**To Reproduce**
1. Subscribe & Enable Mod.

**Output log**
```
First anim file needs to be non-null. LuminiferousSphereComplete (UnityEngine.GameObject)

  at UnityEngine.Debug.LogError (System.Object message) [0x00000] in <72b60a3dd8cd4f12a155b761a1af9144>:0 
  at Debug.LogError (System.Object obj) [0x00000] in <8c239b169b544cce8b8bc7ddd2d09e10>:0 
  at DebugUtil.AssertArgs (System.Boolean test, System.Object[] objs) [0x00000] in <8c239b169b544cce8b8bc7ddd2d09e10>:0 
  at KAnimControllerBase.set_AnimFiles (KAnimFile[] value) [0x00000] in <1c7e9ccb4aa844e2be4538990aabf98e>:0 
  at BuildingLoader.Add2DComponents (BuildingDef def, UnityEngine.GameObject go, System.String initialAnimState, System.Boolean no_collider, System.Int32 layer) [0x00000] in <1c7e9ccb4aa844e2be4538990aabf98e>:0 
  at BuildingLoader.CreateBuildingComplete (UnityEngine.GameObject go, BuildingDef def) [0x00000] in <1c7e9ccb4aa844e2be4538990aabf98e>:0 
  at BuildingConfigManager.RegisterBuilding (IBuildingConfig config) [0x00000] in <1c7e9ccb4aa844e2be4538990aabf98e>:0 
  at GeneratedBuildings.GeneratedBuildings.LoadGeneratedBuildings_Patch18 (System.Collections.Generic.List`1[T] ) [0x00000] in <1c7e9ccb4aa844e2be4538990aabf98e>:0 
  at LegacyModMain.LoadBuildings (System.Collections.Generic.List`1[T] types) [0x00000] in <1c7e9ccb4aa844e2be4538990aabf98e>:0 
  at LegacyModMain.Load () [0x00000] in <1c7e9ccb4aa844e2be4538990aabf98e>:0 
  at Assets.CreatePrefabs () [0x00000] in <1c7e9ccb4aa844e2be4538990aabf98e>:0 
  at Assets.OnPrefabInit () [0x00000] in <1c7e9ccb4aa844e2be4538990aabf98e>:0 
  at KMonoBehaviour.InitializeComponent () [0x00000] in <8c239b169b544cce8b8bc7ddd2d09e10>:0 
  at KMonoBehaviour.Awake () [0x00000] in <8c239b169b544cce8b8bc7ddd2d09e10>:0 
  at UnityEngine.Object.Internal_InstantiateSingleWithParent_Injected (UnityEngine.Object data, UnityEngine.Transform parent, UnityEngine.Vector3& pos, UnityEngine.Quaternion& rot) [0x00000] in <72b60a3dd8cd4f12a155b761a1af9144>:0 
  at UnityEngine.Object.Internal_InstantiateSingleWithParent (UnityEngine.Object data, UnityEngine.Transform parent, UnityEngine.Vector3 pos, UnityEngine.Quaternion rot) [0x00000] in <72b60a3dd8cd4f12a155b761a1af9144>:0 
  at UnityEngine.Object.Instantiate (UnityEngine.Object original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Transform parent) [0x00000] in <72b60a3dd8cd4f12a155b761a1af9144>:0 
  at UnityEngine.Object.Instantiate[T] (T original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Transform parent) [0x00000] in <72b60a3dd8cd4f12a155b761a1af9144>:0 
  at Util.KInstantiate (UnityEngine.GameObject original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.GameObject parent, System.String name, System.Boolean initialize_id, System.Int32 gameLayer) [0x00000] in <8c239b169b544cce8b8bc7ddd2d09e10>:0 
  at Util.KInstantiate (UnityEngine.GameObject original, UnityEngine.GameObject parent, System.String name) [0x00000] in <8c239b169b544cce8b8bc7ddd2d09e10>:0 
  at LaunchInitializer.Update () [0x00000] in <1c7e9ccb4aa844e2be4538990aabf98e>:0 
Build: U42-514967-S
```

**Additional Notes**
I do not agree with disabling steam comment section. This prevents people like me from reporting in the comments that the mod is broken, for additional users to note down for themselves or say that it works for them if it does. Even if -you- do not use it, it stops others from talking to each other about the mod.

**Comment by Oondanomala** [comment] 2022-08-18 19:17
Please check for duplicates before opening an issue.
Duplicate of #129, which includes a fix.

**Comment by Cairath** [comment] 2022-08-18 20:32
Thanks, but don't need you to moderate my repo ;) 

An update has  been pushed to steam a few minutes ago.

Regarding disabling comments on steam - well, you may not agree all you want, the decision is mine. Maybe if people weren't incredibly spammy a few minutes after every tiny update, or spammed "doesn't work!" whenever they forget to enable the mod, modders would not use that feature. Without that feature I probably would have probably removed my mods from steam.

**Closed by Cairath** 2022-08-18 20:32 UTC

**Comment by VasVadum** [comment] 2022-08-18 23:52
> Maybe if people weren't incredibly spammy a few minutes after every tiny update
Yes, I can see why this would be bothersome. People these days have become extremely entitled and all that. Plus Valve made steam worse with the failure to properly auto update mods anymore making matters worse for modders.

> Please check for duplicates before opening an issue.
I did try to skim the open issues. It becomes difficult when all the mods are combined into one repo.
